### ISSUE TITLE
Configurable Products

### ISSUE THREAD

**Issue by shahroq** [r-martins/Magento-OutOfStockLast#5]
Hi,
Extension works great, except for configurable products that all associate products are "out of stock", so although this cofig products are have the "stock availability"="In Stock" they should consider "out of stock". do u have any solution for this?

**Comment by vinidade88** [comment]
Hello,

I need a solution for this too. 
Please, does anybody get this working with configurable and bundle products?

**Comment by michellezhu14** [comment]
Hi.
I have modified the Layer.php file so that it could work for configurable products. But I have no access, could I get the access to push my code?  @r-martins 
Thank you!

**Comment by r-martins** [comment]
Sure @michellezhu14 
Why don't you make a pull request?

**Comment by michellezhu14** [comment]
@r-martins 
Yes, of course.
I have made the pull request, please review.

**Comment by r-martins** [comment]
I've accepted the pull request.
Thank you very much @michellezhu14
